version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo-1
    ports:
      - "27017:27017"
    networks: 
      - production-network
  server:
    build:
      dockerfile: ./docker/server.dockerfile
      context: .
    image: rubenskj/server
    container_name: java-api-1
    ports:
      - "8080:8080"
    networks: 
      - production-network
    depends_on: 
      - "mongo"
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: rubenskj/nginx
    container_name: nginx-1
    ports:
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "server"
networks:
  production-network:
    driver: bridge