version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo-1
    ports:
      - "27017:27017"
  server:
    build:
      dockerfile: ./server.dockerfile
      context: .
    image: rubenskj/server
    container_name: server-1
    ports:
      - "8080:8080"
networks:
  production-network:
    driver: bridge"